workdir: "/home/jana/Documents/1Projects/HoneybeeDemo/"
species: "Apis mellifera"
ploidy: "1"
noChromosomes: 2
vcf: "/home/jana/Documents/1Projects/HoneybeeDemo/Data/Chr1and2Small.vcf"  # Make sure the chromosome numbers are 1:16 (not names)
bcftoolsModule: "igmm/apps/bcftools/1.9"
ancestralAllele: "/home/jana/Documents/1Projects/HoneybeeDemo/Data/AncestralAlleleVcf.txt"
meta: "/home/jana/Documents/1Projects/HoneybeeDemo/Data/Meta.csv"
populations:
  "carnica" : "C"
  "ligustica" : "C"
  "mellifera" : "M"
  "caucasica" : "O"
  "scutellata" : "A"
  "unicolor" : "A"
  "capensis" : "A"
  "hybrid" : "H"
