species: "Apis mellifera"
ploidy: "1"
noChromosomes: 16
vcf: # Make sure the chromosome numbers are 1:16 (not names)
bcftoolsModule: "igmm/apps/bcftools/1.9"
ancestralAllele: ""
meta:
populations:
  "carnica" : "C"
  "ligustica" : "C"
  "mellifera" : "M"
  "caucasica" : "O"
  "scutellata" : "A"
  "unicolor" : "A"
  "capensis" : "A"
  "hybrid" : "H"
